spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pg_mockup
    username : sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

